<?php $_nico_settings  = array (
  'options' => 
  array (
    '.box-product .description, .product-grid .description' => 
    array (
      'display' => 'none',
    ),
  ),
  'settings' => 
  array (
    0 => NULL,
    'phone_number' => '07245465',
    'google_number' => 'google',
    'twitter' => 'http://twitter.com/NicoleThemes',
    'facebook' => 'http://www.facebook.com/pages/Nicole-Themes/201498429982413',
    'sale_text' => '',
    'notification_hide_timeout' => '5000',
    'custom_css' => '',
    'first_visit_message' => '',
    'menu_search' => 'top',
    'menu_language' => 'left',
    'menu_currency' => 'left',
    'product_description' => 'bottom',
    'thumbs_location' => 'left',
    'pinterest' => '',
    'instagram' => '',
    'google' => 'http://www.gplus.com',
    'responsive_css' => 'false',
  ),
  'sliders' => 
  array (
    'Homepage' => 
    array (
      'active' => 'Camera slider',
    ),
    'Product page' => 
    array (
      'Cloud zoom' => 
      array (
        'showTitle' => 'false',
      ),
    ),
  ),
  'background-image' => 'none',
  'background-style' => 'repeat',
  'styles' => 
  array (
    'background_color' => '',
    'page_alignment' => '',
    'catalog_mode' => '',
  ),
  'menu' => 
  array (
    0 => 
    array (
      'url' => 'information/news.html',
      'text' => 
      array (
        'ro' => 'News',
        'en' => 'News',
      	'ru' => 'Новости',
      ),
    ),
    /*1 => 
    array (
      'url' => '/index.php?route=product/category&amp;path=20_27',
      'text' => 
      array (
        'ro' => 'Meniu customizat',
        'en' => 'Custom menu',
      ),
      'children' => 
      array (
        0 => 
        array (
          'url' => '/index.php?route=product/category&amp;path=20_27',
          'text' => 
          array (
            'en' => 'Subcat 1',
          ),
        ),
        1 => 
        array (
          'url' => '/index.php?route=product/category&amp;path=20_27',
          'text' => 
          array (
            'en' => 'Subcat 2',
          ),
        ),
        2 => 
        array (
          'url' => '/index.php?route=product/category&amp;path=20_27',
          'text' => 
          array (
            'en' => 'Subcat 3',
          ),
        ),
      ),
    ),
    2 => 
    array (
      'url' => '/index.php?route=product/category&amp;path=20_27',
      'text' => 
      array (
        'en' => 'Custom link',
      ),
    ),*/
    1 => 
    array (
      'text' => 
      array (
        'en' => 'Categories',
      	'ru' => 'Категории',
      ),
      'children' => 
      array (
        0 => 
        array (
          'categories' => 'true',
        ),
      ),
    ),
  ),
);