<?php $_nico_settings  = array (
  'options' => 
  array (
    '#currency' => 
    array (
      'display' => 'block',
    ),
    '#language' => 
    array (
      'display' => 'block',
    ),
    '#social_band' => 
    array (
      'display' => 'none',
    ),
    '.payment-icons' => 
    array (
      'display' => 'block',
    ),
    '.category-info' => 
    array (
      'display' => 'none',
    ),
    '.share' => 
    array (
      'display' => 'block',
    ),
    '.box-product .description, .product-grid .description' => 
    array (
      'display' => 'none',
    ),
  ),
  'settings' => 
  array (
    0 => NULL,
    'phone_number' => '07245465',
    'google_number' => 'google',
    'twitter' => 'http://twitter.com/NicoleThemes',
    'facebook' => 'http://www.facebook.com/pages/Nicole-Themes/201498429982413',
    'sale_text' => '-20%',
    'notification_hide_timeout' => '5000',
    'custom_css' => '',
    'first_visit_message' => '',
    'menu_search' => 'top',
    'menu_language' => 'left',
    'menu_currency' => 'left',
    'product_description' => 'bottom',
    'thumbs_location' => 'left',
    'pinterest' => '',
    'instagram' => 'http://www.instagram.com',
    'google' => 'http://www.gplus.com',
  ),
  'sliders' => 
  array (
    'Homepage' => 
    array (
      'active' => 'Camera slider',
    ),
    'Product page' => 
    array (
      'Cloud zoom' => 
      array (
        'showTitle' => 'false',
      ),
    ),
  ),
  'background-image' => 'none',
  'background-style' => 'repeat',
  'styles' => 
  array (
    'background_color' => '',
    'page_alignment' => '',
    'menu_alignment' => '',
    'logo_background' => 'logo_background-black.css',
    'product_name_alignment' => 'product_name_alignment-center.css',
  ),
  'menu' => 
  array (
    0 => 
    array (
      'url' => 'index.php?route=pavblog/blogs',
      'text' => 
      array (
        'ro' => 'Blog',
        'en' => 'Blog',
      ),
    ),
    1 => 
    array (
      'url' => '/index.php?route=product/category&amp;path=20_27',
      'text' => 
      array (
        'en' => 'Custom menu',
      ),
      'children' => 
      array (
        0 => 
        array (
          'url' => '/index.php?route=product/category&amp;path=20_27',
          'text' => 
          array (
            'en' => 'Subcat 1',
          ),
        ),
        1 => 
        array (
          'url' => '/index.php?route=product/category&amp;path=20_27',
          'text' => 
          array (
            'en' => 'Subcat 2',
          ),
        ),
        2 => 
        array (
          'url' => '/index.php?route=product/category&amp;path=20_27',
          'text' => 
          array (
            'en' => 'Subcat 3',
          ),
        ),
      ),
    ),
    2 => 
    array (
      'url' => '/index.php?route=product/category&amp;path=20_27',
      'text' => 
      array (
        'en' => 'Custom link',
      ),
    ),
    3 => 
    array (
      'text' => 
      array (
        'en' => 'Categories',
      ),
      'children' => 
      array (
        0 => 
        array (
          'categories' => 'true',
        ),
      ),
    ),
  ),
);